export const config = {
  developer: {
    name: "Mervin A",
    title: "2nd year student at Christ University",
    bio: "B.Tech Computer Science Engineering (AIML) student with hands-on experience in web development and software projects. Seeking a software engineering internship to apply and grow technical skills.",
    avatar: "https://i.pinimg.com/736x/d4/a5/f5/d4a5f585a3470cf0c42458970be37dbc.jpg",
  },
  social: {
    github: "Mervin0266",
    email: "mervin0266@gmail.com",
    location: "Bengaluru, Karnataka, India",
  },
  projects: [
    {
      id: 1,
      title: "MuteBreaker – Sign Language to Speech Converter",
      description: "Developed the complete software pipeline for a glove-based assistive system, including analysis and processing of raw sensor data for gesture recognition, and built a real-time web interface that generates both text and speech output.",
      image: "/projects/project-1-v2.webp",
      technologies: ["Flutter", "ESP32", "Flex Sensors"],
      github: "#",
      demo: "#",
    },
    {
      id: 2,
      title: "Python Mini Projects & Games",
      description: "Built multiple Python mini projects and games using OOP and core Python concepts, working with libraries such as Pandas, handling CSV files, and developing applications with Tkinter and Turtle, along with implementing basic SMTP functionality.",
      image: "/projects/project-2-v2.webp",
      technologies: ["Python", "Pandas", "Tkinter", "Turtle", "SMTP"],
      github: "https://github.com/Mervin0266/100-days-of-python.git",
      demo: "#",
    },
    {
      id: 3,
      title: "Mars Rover – Autonomous Navigation System",
      description: "Built a rover prototype with sensor-based obstacle detection and navigation logic, implemented AI-based path planning for uneven terrain, and enabled real-time data transmission for monitoring.",
      image: "/projects/project-3-v2.webp",
      technologies: ["Arduino UNO", "HC05", "l289n", "Ultrasonic Sensor", "AI Path Planning"],
      github: "#",
      demo: "#",
    },
    {
      id: 4,
      title: "Multifunctional Robot – Fire Detection & Human Follower",
      description: "Developed autonomous fire detection and response functionality and implemented human-following behavior using sensor data.",
      image: "/projects/project-4-v3.webp",
      technologies: ["Arduino UNO", "DHT11", "l289n", "Ultrasonic Sensor", "AI Path Planning"],
      github: "#",
      demo: "#",
    },
  ],
  skills: [
    { name: "React.js", icon: "react" },
    { name: "Python", icon: "python" },
    { name: "PostgreSQL", icon: "postgresql" },
    { name: "C", icon: "c" },
    { name: "TypeScript", icon: "typescript" },
    { name: "JavaScript", icon: "javascript" },
    { name: "TailwindCSS", icon: "tailwind" },
    { name: "Git", icon: "git" },
    // { name: "Next.js", icon: "nextjs" },
    // { name: "Node.js", icon: "nodejs" },
    // { name: "MongoDB", icon: "mongodb" },
    // { name: "Express", icon: "express" },
    // { name: "AWS", icon: "aws" },
    // { name: "Docker", icon: "docker" },
    // { name: "Framer Motion", icon: "framer" },
  ],
};

